// <auto-generated />
using System;
using System.Collections.Generic;
using Crm.Domain.RiskEngine;
using Crm.Infrastructure.Adapters.Outbound.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Crm.Infrastructure.Migrations
{
    [DbContext(typeof(CrmDbContext))]
    partial class CrmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Crm.Domain.ApprovalWorkflows.ApprovalDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("CreditApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("credit_application_id");

                    b.Property<DateTime>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<string>("DecidedBy")
                        .HasColumnType("text")
                        .HasColumnName("decided_by");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("decision");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<Guid?>("WorkflowDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_definition_id");

                    b.Property<Guid?>("WorkflowStepId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_step_id");

                    b.HasKey("Id")
                        .HasName("approval_decisions_pkey");

                    b.HasIndex(new[] { "CreditApplicationId" }, "ix_approval_decisions_application");

                    b.ToTable("approval_decisions", (string)null);
                });

            modelBuilder.Entity("Crm.Domain.ApprovalWorkflows.WorkflowDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Draft'::text");

                    b.HasKey("Id")
                        .HasName("workflow_definitions_pkey");

                    b.HasIndex(new[] { "Status" }, "ix_workflow_definitions_status");

                    b.ToTable("workflow_definitions", (string)null);
                });

            modelBuilder.Entity("Crm.Domain.ApprovalWorkflows.WorkflowStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<string>("RequiredRole")
                        .HasColumnType("text")
                        .HasColumnName("required_role");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("step_name");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_definition_id");

                    b.HasKey("Id")
                        .HasName("workflow_steps_pkey");

                    b.HasIndex(new[] { "WorkflowDefinitionId" }, "ix_workflow_steps_definition");

                    b.ToTable("workflow_steps", (string)null);
                });

            modelBuilder.Entity("Crm.Domain.CreditApplications.ApplicationDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("CreditApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("credit_application_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Uploaded'::text");

                    b.Property<string>("StorageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_url");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("application_documents_pkey");

                    b.HasIndex(new[] { "CreditApplicationId" }, "ix_application_documents_application");

                    b.ToTable("application_documents", (string)null);
                });

            modelBuilder.Entity("Crm.Domain.CreditApplications.CreditApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ProspectId")
                        .HasColumnType("uuid")
                        .HasColumnName("prospect_id");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Draft'::text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("WorkflowDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_definition_id");

                    b.HasKey("Id")
                        .HasName("credit_applications_pkey");

                    b.HasIndex(new[] { "ProspectId" }, "ix_credit_applications_prospect");

                    b.ToTable("credit_applications", (string)null);
                });

            modelBuilder.Entity("Crm.Domain.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("CreditScore")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("credit_score");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("ExternalCode")
                        .HasColumnType("text")
                        .HasColumnName("external_code");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("IdentificationNumber")
                        .HasColumnType("text")
                        .HasColumnName("identification_number");

                    b.Property<string>("IdentificationType")
                        .HasColumnType("text")
                        .HasColumnName("identification_type");

                    b.Property<decimal?>("MonthlyDebt")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monthly_debt");

                    b.Property<decimal?>("MonthlyIncome")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monthly_income");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'ACTIVE'::text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("customers_pkey");

                    b.HasIndex(new[] { "FullName" }, "ix_customers_full_name");

                    b.HasIndex(new[] { "IdentificationNumber" }, "ix_customers_identification");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Crm.Domain.Customers.CustomerDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("StorageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_url");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("customer_documents_pkey");

                    b.HasIndex(new[] { "CustomerId" }, "ix_customer_documents_customer");

                    b.ToTable("customer_documents", (string)null);
                });

            modelBuilder.Entity("Crm.Domain.Customers.ExternalCustomerRef", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_id");

                    b.Property<string>("LegalName")
                        .HasColumnType("text")
                        .HasColumnName("legal_name");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<decimal?>("RiskScore")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("risk_score");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("customers_ref_pkey");

                    b.HasIndex(new[] { "ExternalId" }, "customers_ref_external_id_key")
                        .IsUnique();

                    b.HasIndex(new[] { "ExternalId" }, "ix_customers_ref_external");

                    b.ToTable("customers_ref", (string)null);
                });

            modelBuilder.Entity("Crm.Domain.Documents.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("DocumentTypeCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("document_type_code");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Uploaded'::text");

                    b.Property<string>("StorageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_url");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("documents_pkey");

                    b.HasIndex(new[] { "OwnerId", "OwnerType" }, "ix_documents_owner");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("Crm.Domain.Documents.DocumentType", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_required");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Code")
                        .HasName("document_types_pkey");

                    b.ToTable("document_types", (string)null);
                });

            modelBuilder.Entity("Crm.Domain.Documents.DocumentValidation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("decision");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("text")
                        .HasColumnName("reviewed_by");

                    b.HasKey("Id")
                        .HasName("document_validations_pkey");

                    b.HasIndex(new[] { "DocumentId" }, "ix_document_validations_document");

                    b.ToTable("document_validations", (string)null);
                });

            modelBuilder.Entity("Crm.Domain.Prospects.Prospect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identification_number");

                    b.Property<string>("IdentificationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identification_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Draft'::text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("prospects_pkey");

                    b.HasIndex(new[] { "IdentificationType", "IdentificationNumber" }, "ux_prospects_identification")
                        .IsUnique();

                    b.ToTable("prospects", (string)null);
                });

            modelBuilder.Entity("Crm.Domain.RiskEngine.RiskEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("CreditApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("credit_application_id");

                    b.Property<DateTime>("EvaluatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evaluated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<Guid>("RiskMatrixId")
                        .HasColumnType("uuid")
                        .HasColumnName("risk_matrix_id");

                    b.Property<int>("RiskMatrixVersion")
                        .HasColumnType("integer")
                        .HasColumnName("risk_matrix_version");

                    b.Property<decimal?>("SuggestedInterestRate")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("suggested_interest_rate");

                    b.Property<decimal?>("SuggestedMaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("suggested_max_amount");

                    b.Property<decimal>("TotalScore")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("total_score");

                    b.HasKey("Id")
                        .HasName("risk_evaluations_pkey");

                    b.HasIndex(new[] { "CreditApplicationId" }, "ix_risk_evaluations_application");

                    b.HasIndex(new[] { "RiskMatrixId" }, "ix_risk_evaluations_matrix");

                    b.ToTable("risk_evaluations", (string)null);
                });

            modelBuilder.Entity("Crm.Domain.RiskEngine.RiskMatrix", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<decimal>("AutoApproveThreshold")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("auto_approve_threshold");

                    b.Property<decimal>("AutoRejectThreshold")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("auto_reject_threshold");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<List<PricingBand>>("PricingBands")
                        .HasColumnType("jsonb")
                        .HasColumnName("pricing_bands");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Draft'::text");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("risk_matrices_pkey");

                    b.HasIndex(new[] { "Status" }, "ix_risk_matrices_status");

                    b.ToTable("risk_matrices", (string)null);
                });

            modelBuilder.Entity("Crm.Domain.RiskEngine.RiskMatrixRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("RiskMatrixId")
                        .HasColumnType("uuid")
                        .HasColumnName("risk_matrix_id");

                    b.Property<Guid>("RiskRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("risk_rule_id");

                    b.HasKey("Id")
                        .HasName("risk_matrix_rules_pkey");

                    b.HasIndex("RiskRuleId");

                    b.HasIndex(new[] { "RiskMatrixId" }, "ix_risk_matrix_rules_matrix");

                    b.ToTable("risk_matrix_rules", (string)null);
                });

            modelBuilder.Entity("Crm.Domain.RiskEngine.RiskRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Dictionary<string, string>>("Parameters")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parameters");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rule_type");

                    b.Property<string>("TargetField")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_field");

                    b.Property<decimal>("Weight")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("risk_rules_pkey");

                    b.ToTable("risk_rules", (string)null);
                });

            modelBuilder.Entity("Crm.Domain.RiskEngine.ScoreCardEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("ObservedValue")
                        .HasColumnType("text")
                        .HasColumnName("observed_value");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean")
                        .HasColumnName("passed");

                    b.Property<Guid>("RiskEvaluationId")
                        .HasColumnType("uuid")
                        .HasColumnName("risk_evaluation_id");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_id");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rule_name");

                    b.Property<string>("TargetField")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_field");

                    b.Property<decimal>("WeightedContribution")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("weighted_contribution");

                    b.HasKey("Id")
                        .HasName("score_card_entries_pkey");

                    b.HasIndex(new[] { "RiskEvaluationId" }, "ix_score_card_entries_evaluation");

                    b.ToTable("score_card_entries", (string)null);
                });

            modelBuilder.Entity("Crm.Domain.ApprovalWorkflows.WorkflowStep", b =>
                {
                    b.HasOne("Crm.Domain.ApprovalWorkflows.WorkflowDefinition", "WorkflowDefinition")
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("workflow_steps_definition_id_fkey");

                    b.Navigation("WorkflowDefinition");
                });

            modelBuilder.Entity("Crm.Domain.CreditApplications.ApplicationDocument", b =>
                {
                    b.HasOne("Crm.Domain.CreditApplications.CreditApplication", "CreditApplication")
                        .WithMany("Documents")
                        .HasForeignKey("CreditApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("application_documents_credit_application_id_fkey");

                    b.Navigation("CreditApplication");
                });

            modelBuilder.Entity("Crm.Domain.Customers.Customer", b =>
                {
                    b.OwnsMany("Crm.Domain.ValueObjects.Address", "CustomerAddresses", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id")
                                .HasDefaultValueSql("uuid_generate_v4()");

                            b1.Property<string>("City")
                                .HasColumnType("text")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .HasColumnType("text")
                                .HasColumnName("country");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at")
                                .HasDefaultValueSql("now()");

                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid")
                                .HasColumnName("customer_id");

                            b1.Property<string>("District")
                                .HasColumnType("text")
                                .HasColumnName("district");

                            b1.Property<bool?>("IsPrimary")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("is_primary");

                            b1.Property<string>("Metadata")
                                .HasColumnType("jsonb")
                                .HasColumnName("metadata");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("text")
                                .HasColumnName("postal_code");

                            b1.Property<string>("State")
                                .HasColumnType("text")
                                .HasColumnName("state");

                            b1.Property<string>("Street")
                                .HasColumnType("text")
                                .HasColumnName("street");

                            b1.Property<string>("Type")
                                .HasColumnType("text")
                                .HasColumnName("type");

                            b1.Property<DateTime>("UpdatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at")
                                .HasDefaultValueSql("now()");

                            b1.HasKey("Id");

                            b1.HasIndex("CustomerId");

                            b1.ToTable("customer_addresses", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsMany("Crm.Domain.ValueObjects.EmailContact", "CustomerEmails", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id")
                                .HasDefaultValueSql("uuid_generate_v4()");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at")
                                .HasDefaultValueSql("now()");

                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid")
                                .HasColumnName("customer_id");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("email");

                            b1.Property<bool?>("IsPrimary")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("is_primary");

                            b1.Property<bool?>("Verified")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("verified");

                            b1.HasKey("Id");

                            b1.HasIndex("CustomerId");

                            b1.ToTable("customer_emails", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsMany("Crm.Domain.ValueObjects.FiscalInfo", "CustomerFiscalInfos", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id")
                                .HasDefaultValueSql("uuid_generate_v4()");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at")
                                .HasDefaultValueSql("now()");

                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid")
                                .HasColumnName("customer_id");

                            b1.Property<string>("EconomicActivity")
                                .HasColumnType("text")
                                .HasColumnName("economic_activity");

                            b1.Property<string>("Industry")
                                .HasColumnType("text")
                                .HasColumnName("industry");

                            b1.Property<string>("Metadata")
                                .HasColumnType("jsonb")
                                .HasColumnName("metadata");

                            b1.Property<string>("TaxId")
                                .HasColumnType("text")
                                .HasColumnName("tax_id");

                            b1.Property<string>("TaxRegime")
                                .HasColumnType("text")
                                .HasColumnName("tax_regime");

                            b1.Property<DateTime>("UpdatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at")
                                .HasDefaultValueSql("now()");

                            b1.HasKey("Id");

                            b1.HasIndex("CustomerId");

                            b1.ToTable("customer_fiscal_info", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsMany("Crm.Domain.ValueObjects.PhoneContact", "CustomerPhones", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id")
                                .HasDefaultValueSql("uuid_generate_v4()");

                            b1.Property<string>("CountryCode")
                                .HasColumnType("text")
                                .HasColumnName("country_code");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at")
                                .HasDefaultValueSql("now()");

                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid")
                                .HasColumnName("customer_id");

                            b1.Property<bool?>("IsPrimary")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("is_primary");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("number");

                            b1.Property<string>("Type")
                                .HasColumnType("text")
                                .HasColumnName("type");

                            b1.Property<bool?>("Verified")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("verified");

                            b1.HasKey("Id");

                            b1.HasIndex("CustomerId");

                            b1.ToTable("customer_phones", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsMany("Crm.Domain.ValueObjects.WorkInfo", "CustomerWorkInfos", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id")
                                .HasDefaultValueSql("uuid_generate_v4()");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at")
                                .HasDefaultValueSql("now()");

                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid")
                                .HasColumnName("customer_id");

                            b1.Property<string>("EmployerName")
                                .HasColumnType("text")
                                .HasColumnName("employer_name");

                            b1.Property<string>("Metadata")
                                .HasColumnType("jsonb")
                                .HasColumnName("metadata");

                            b1.Property<string>("Occupation")
                                .HasColumnType("text")
                                .HasColumnName("occupation");

                            b1.Property<decimal?>("Salary")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("salary");

                            b1.Property<DateTime>("UpdatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at")
                                .HasDefaultValueSql("now()");

                            b1.Property<string>("WorkAddress")
                                .HasColumnType("jsonb")
                                .HasColumnName("work_address");

                            b1.HasKey("Id");

                            b1.HasIndex("CustomerId");

                            b1.ToTable("customer_work_info", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.Navigation("CustomerAddresses");

                    b.Navigation("CustomerEmails");

                    b.Navigation("CustomerFiscalInfos");

                    b.Navigation("CustomerPhones");

                    b.Navigation("CustomerWorkInfos");
                });

            modelBuilder.Entity("Crm.Domain.Customers.CustomerDocument", b =>
                {
                    b.HasOne("Crm.Domain.Customers.Customer", "Customer")
                        .WithMany("CustomerDocuments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("customer_documents_customer_id_fkey");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Crm.Domain.Documents.DocumentValidation", b =>
                {
                    b.HasOne("Crm.Domain.Documents.Document", "Document")
                        .WithMany("Validations")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("document_validations_document_id_fkey");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Crm.Domain.Prospects.Prospect", b =>
                {
                    b.OwnsMany("Crm.Domain.ValueObjects.Address", "Addresses", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id")
                                .HasDefaultValueSql("uuid_generate_v4()");

                            b1.Property<string>("City")
                                .HasColumnType("text")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .HasColumnType("text")
                                .HasColumnName("country");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at")
                                .HasDefaultValueSql("now()");

                            b1.Property<string>("District")
                                .HasColumnType("text")
                                .HasColumnName("district");

                            b1.Property<bool?>("IsPrimary")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("is_primary");

                            b1.Property<string>("Metadata")
                                .HasColumnType("jsonb")
                                .HasColumnName("metadata");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("text")
                                .HasColumnName("postal_code");

                            b1.Property<Guid>("ProspectId")
                                .HasColumnType("uuid")
                                .HasColumnName("prospect_id");

                            b1.Property<string>("State")
                                .HasColumnType("text")
                                .HasColumnName("state");

                            b1.Property<string>("Street")
                                .HasColumnType("text")
                                .HasColumnName("street");

                            b1.Property<string>("Type")
                                .HasColumnType("text")
                                .HasColumnName("type");

                            b1.Property<DateTime>("UpdatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at")
                                .HasDefaultValueSql("now()");

                            b1.HasKey("Id");

                            b1.HasIndex("ProspectId");

                            b1.ToTable("prospect_addresses", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProspectId");
                        });

                    b.OwnsMany("Crm.Domain.ValueObjects.EmailContact", "Emails", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id")
                                .HasDefaultValueSql("uuid_generate_v4()");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at")
                                .HasDefaultValueSql("now()");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("email");

                            b1.Property<bool?>("IsPrimary")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("is_primary");

                            b1.Property<Guid>("ProspectId")
                                .HasColumnType("uuid")
                                .HasColumnName("prospect_id");

                            b1.Property<bool?>("Verified")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("verified");

                            b1.HasKey("Id");

                            b1.HasIndex("ProspectId");

                            b1.ToTable("prospect_emails", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProspectId");
                        });

                    b.OwnsMany("Crm.Domain.ValueObjects.FiscalInfo", "FiscalInfos", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id")
                                .HasDefaultValueSql("uuid_generate_v4()");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at")
                                .HasDefaultValueSql("now()");

                            b1.Property<string>("EconomicActivity")
                                .HasColumnType("text")
                                .HasColumnName("economic_activity");

                            b1.Property<string>("Industry")
                                .HasColumnType("text")
                                .HasColumnName("industry");

                            b1.Property<string>("Metadata")
                                .HasColumnType("jsonb")
                                .HasColumnName("metadata");

                            b1.Property<Guid>("ProspectId")
                                .HasColumnType("uuid")
                                .HasColumnName("prospect_id");

                            b1.Property<string>("TaxId")
                                .HasColumnType("text")
                                .HasColumnName("tax_id");

                            b1.Property<string>("TaxRegime")
                                .HasColumnType("text")
                                .HasColumnName("tax_regime");

                            b1.Property<DateTime>("UpdatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at")
                                .HasDefaultValueSql("now()");

                            b1.HasKey("Id");

                            b1.HasIndex("ProspectId");

                            b1.ToTable("prospect_fiscal_info", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProspectId");
                        });

                    b.OwnsMany("Crm.Domain.ValueObjects.PhoneContact", "Phones", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id")
                                .HasDefaultValueSql("uuid_generate_v4()");

                            b1.Property<string>("CountryCode")
                                .HasColumnType("text")
                                .HasColumnName("country_code");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at")
                                .HasDefaultValueSql("now()");

                            b1.Property<bool?>("IsPrimary")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("is_primary");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("number");

                            b1.Property<Guid>("ProspectId")
                                .HasColumnType("uuid")
                                .HasColumnName("prospect_id");

                            b1.Property<string>("Type")
                                .HasColumnType("text")
                                .HasColumnName("type");

                            b1.Property<bool?>("Verified")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("verified");

                            b1.HasKey("Id");

                            b1.HasIndex("ProspectId");

                            b1.ToTable("prospect_phones", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProspectId");
                        });

                    b.OwnsMany("Crm.Domain.ValueObjects.WorkInfo", "WorkInfos", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id")
                                .HasDefaultValueSql("uuid_generate_v4()");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at")
                                .HasDefaultValueSql("now()");

                            b1.Property<string>("EmployerName")
                                .HasColumnType("text")
                                .HasColumnName("employer_name");

                            b1.Property<string>("Metadata")
                                .HasColumnType("jsonb")
                                .HasColumnName("metadata");

                            b1.Property<string>("Occupation")
                                .HasColumnType("text")
                                .HasColumnName("occupation");

                            b1.Property<Guid>("ProspectId")
                                .HasColumnType("uuid")
                                .HasColumnName("prospect_id");

                            b1.Property<decimal?>("Salary")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("salary");

                            b1.Property<DateTime>("UpdatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at")
                                .HasDefaultValueSql("now()");

                            b1.Property<string>("WorkAddress")
                                .HasColumnType("text")
                                .HasColumnName("work_address");

                            b1.HasKey("Id");

                            b1.HasIndex("ProspectId");

                            b1.ToTable("prospect_work_info", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProspectId");
                        });

                    b.Navigation("Addresses");

                    b.Navigation("Emails");

                    b.Navigation("FiscalInfos");

                    b.Navigation("Phones");

                    b.Navigation("WorkInfos");
                });

            modelBuilder.Entity("Crm.Domain.RiskEngine.RiskMatrixRule", b =>
                {
                    b.HasOne("Crm.Domain.RiskEngine.RiskMatrix", "RiskMatrix")
                        .WithMany("MatrixRules")
                        .HasForeignKey("RiskMatrixId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("risk_matrix_rules_matrix_id_fkey");

                    b.HasOne("Crm.Domain.RiskEngine.RiskRule", "RiskRule")
                        .WithMany()
                        .HasForeignKey("RiskRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("risk_matrix_rules_rule_id_fkey");

                    b.Navigation("RiskMatrix");

                    b.Navigation("RiskRule");
                });

            modelBuilder.Entity("Crm.Domain.RiskEngine.ScoreCardEntry", b =>
                {
                    b.HasOne("Crm.Domain.RiskEngine.RiskEvaluation", "RiskEvaluation")
                        .WithMany("Entries")
                        .HasForeignKey("RiskEvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("score_card_entries_evaluation_id_fkey");

                    b.Navigation("RiskEvaluation");
                });

            modelBuilder.Entity("Crm.Domain.ApprovalWorkflows.WorkflowDefinition", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Crm.Domain.CreditApplications.CreditApplication", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Crm.Domain.Customers.Customer", b =>
                {
                    b.Navigation("CustomerDocuments");
                });

            modelBuilder.Entity("Crm.Domain.Documents.Document", b =>
                {
                    b.Navigation("Validations");
                });

            modelBuilder.Entity("Crm.Domain.RiskEngine.RiskEvaluation", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Crm.Domain.RiskEngine.RiskMatrix", b =>
                {
                    b.Navigation("MatrixRules");
                });
#pragma warning restore 612, 618
        }
    }
}
